### ISSUE TITLE
Stop foreach when certain item is found

### ISSUE THREAD

**Issue by SnooHD** [IndigoUnited/js-deep-for-each#25]
Hello, thanks for working on this!
I am using this package to find a object in a nested object and then manipulate it.
Now after i found it, i dont need to continue the loop.
Is there a way to stop the foreach?

Thanks!

**Comment by acostalima** [comment]
@SnooHD [Lodash's get()](https://lodash.com/docs/#get) would be a better fit for what you want to achieve.

**Comment by satazor** [comment]
Sorry for the late response. I guess what you are asking is out of the scope of this module. It sounds like a role for a `deep-find` module instead.
