### ISSUE TITLE
Example about how to manipulate iterated object

### ISSUE THREAD

**Issue by Vadorequest** [IndigoUnited/js-deep-for-each#37]
Could you add an example about how to manipulate the iterated object?

Listing properties is very easy, but how would you do it if you need to update the values while looping on it? Make a clone and update the clone? Is there a way to get the reference of the current iterated element? I tried `subject` but it looks like a copy, not a reference.

**Comment by satazor** [comment]
`subject` is a reference, you just need to do `subject[key] = newValue`.

Will close and re-open if necessary.
